### ISSUE TITLE
Server is crashing

### ISSUE THREAD

**Issue by Draakoor** [NomisCZ/sm_skinchooser#1]
L 08/28/2016 - 17:02:15: SourceMod error session started
L 08/28/2016 - 17:02:15: Info (map "pl_upward") (file "errors_20160828.log")
L 08/28/2016 - 17:02:15: [SM] Exception reported: Invalid key value handle 0 (error 4)
L 08/28/2016 - 17:02:15: [SM] Blaming: sm_skinchooser.smx()
L 08/28/2016 - 17:02:15: [SM] Call stack trace:
L 08/28/2016 - 17:02:15: [SM]   [0] KvJumpToKey
L 08/28/2016 - 17:02:15: [SM]   [1] Line 1541, D:\csgo\csgo\addons\sourcemod\scripting\sm_skinchooser4.0.sp::Event_PlayerSpawn()
L 08/28/2016 - 17:12:14: [SM] Exception reported: Invalid key value handle 0 (error 4)
L 08/28/2016 - 17:12:14: [SM] Blaming: sm_skinchooser.smx()
L 08/28/2016 - 17:12:14: [SM] Call stack trace:
L 08/28/2016 - 17:12:14: [SM]   [0] KeyValuesToFile
L 08/28/2016 - 17:12:14: [SM]   [1] Line 409, D:\csgo\csgo\addons\sourcemod\scripting\sm_skinchooser4.0.sp::OnMapEnd()
L 08/28/2016 - 17:12:15: Error log file session closed.
L 08/28/2016 - 17:12:28: SourceMod error session started
L 08/28/2016 - 17:12:28: Info (map "pl_upward") (file "errors_20160828.log")
L 08/28/2016 - 17:12:28: [SM] Exception reported: Invalid key value handle 0 (error 4)
L 08/28/2016 - 17:12:28: [SM] Blaming: sm_skinchooser.smx()
L 08/28/2016 - 17:12:28: [SM] Call stack trace:
L 08/28/2016 - 17:12:28: [SM]   [0] KvJumpToKey
L 08/28/2016 - 17:12:28: [SM]   [1] Line 1606, sm_skinchooser.sp::Event_PlayerSpawn()

**Comment by NomisCZ** [comment]
Hi, 
please send me your configs (addons/sourcemod/configs/sm_skinchooser) _(http://pastebin.com)_. I think that's one mistake.

**Comment by Draakoor** [comment]
http://pastebin.com/stiBgE9z

**Comment by NomisCZ** [comment]
**1. You have syntax error in default_arms.ini**. You **can't use "path"** in **arms config.**
>"Arms"
>{
> "Public Models"
>     {
>         "Admin" ""
>         "Team1"
>         {
>             "Scout"
>             {
>                 **"path"** "models/player/custom_player/kuristaja/tf2/sniper/scout_red_arms.mdl"
>             }
>             "Soldier"
>             {
>                 **"path"** "models/player/custom_player/kuristaja/tf2/sniper/soldier_red_arms.mdl"
>             }
> ...

» **Rewrite "path" to "arms"** https://github.com/NomisCZ/sm_skinchooser/blob/master/addons/sourcemod/configs/sm_skinchooser/default_arms.ini)

**2. Do you have other configs (forceskinXX_teamX.ini) in sm_skinchooser folder?**
» https://github.com/NomisCZ/sm_skinchooser/tree/master/addons/sourcemod/configs/sm_skinchooser
